# Generated by Django 3.0.8 on 2020-07-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=160, unique_for_date="published_at"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=600, verbose_name="description"),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "is_published",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="is published"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="published at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={"verbose_name": "article", "verbose_name_plural": "articles",},
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-created_at"], name="articles_ar_created_312397_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_published", "-published_at"],
                name="articles_ar_is_publ_08ff0b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["slug", "published_at"], name="articles_ar_slug_d41be1_idx"
            ),
        ),
    ]
