# Generated by Django 3.0.8 on 2020-07-11 13:38

import apps.articles.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Article main image",
                max_length=150,
                null=True,
                upload_to=apps.articles.storage.article_image_upload_to,
                verbose_name="image",
            ),
        ),
    ]
