# Generated by Django 3.0.8 on 2020-07-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_featured",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Mark an article as a featured on home page",
                verbose_name="is featured",
            ),
        ),
    ]
