# Generated by Django 3.0.8 on 2020-07-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="comments_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of comments associated with this article. Calculates automatically after posting each comment.",
                verbose_name="number of comments",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-comments_count"], name="articles_ar_comment_9ee4dc_idx"
            ),
        ),
    ]
