# Generated by Django 3.0.8 on 2020-07-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_article_comments_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_category_featured",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="is category featured"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_category_featured"], name="articles_ar_is_cate_3989c1_idx"
            ),
        ),
    ]
